name: ia_incidencias_svm
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas
  - numpy
  - scikit-learn
  - pip:
      - torch
      - torchvision
      - torchaudio
      - --index-url https://download.pytorch.org/whl/cpu
      - sentence-transformers
      - fastapi[standard]
      - uvicorn
      - joblib
      - pymysql
      - requests